// <auto-generated />
using Arsenals.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arsenals.Infrastructure.Ef.Migrations
{
    [DbContext(typeof(ArsenalDbContext))]
    [Migration("20240819132434_Fix-Bullet-FK")]
    partial class FixBulletFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Bullets.BulletData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Damage")
                        .HasColumnType("integer")
                        .HasColumnName("damage");

                    b.Property<int>("GunDataId")
                        .HasColumnType("integer")
                        .HasColumnName("gun_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GunDataId");

                    b.HasIndex("Name");

                    b.ToTable("bullets");
                });

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Guns.GunCategoryData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("gun_categories");
                });

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Guns.GunData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("GunCategoryDataId")
                        .HasColumnType("integer")
                        .HasColumnName("gun_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GunCategoryDataId");

                    b.HasIndex("Name");

                    b.ToTable("guns");
                });

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Bullets.BulletData", b =>
                {
                    b.HasOne("Arsenals.Infrastructure.Ef.Guns.GunData", "GunData")
                        .WithMany("BulletDataList")
                        .HasForeignKey("GunDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GunData");
                });

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Guns.GunData", b =>
                {
                    b.HasOne("Arsenals.Infrastructure.Ef.Guns.GunCategoryData", "GunCategoryData")
                        .WithMany()
                        .HasForeignKey("GunCategoryDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GunCategoryData");
                });

            modelBuilder.Entity("Arsenals.Infrastructure.Ef.Guns.GunData", b =>
                {
                    b.Navigation("BulletDataList");
                });
#pragma warning restore 612, 618
        }
    }
}
